enum class Variable {
    PROGRAM,
    PROGRAM_HEADER,
    DECLARATION_PART,
    CONST_DECLARATION,
    CONSTANT, // 5
    TYPE_DECLARATION,
    VAR_DECLARATION,
    IDENTIFIER_LIST,
    TYPE,
    ARRAY_TYPE, // 10
    RANGE,
    ENUMERATED,
    RECORD_TYPE,
    FIELD_LIST,
    FIELD_PART, // 15
    SUBPROGRAM_DECLARATION,
    PROCEDURE_DECLARATION,
    FUNCTION_DECLARATION,
    BLOCK,
    FORMAL_PARAMETER_LIST, // 20
    PARAMETER_GROUP,
    COMPOUND_STATEMENT,
    STATEMENT_LIST,
    STATEMENT,
    ASSIGNMENT_STATEMENT, // 25
    IF_STATEMENT,
    CASE_STATEMENT,
    CASE_BLOCK,
    WHILE_STATEMENT,
    REPEAT_STATEMENT, // 30
    FOR_STATEMENT,
    PROCEDURE_OR_FUNCTION_CALL, // <procedure/function-call>
    PARAMETER_LIST,
    EXPRESSION,
    SIMPLE_EXPRESSION, //35
    TERM,
    FACTOR,
    RELATIONAL_OPERATOR,
    ADDITIVE_OPERATOR,
    MULTIPLICATIVE_OPERATOR
};